'use client'
import "./globals.css"
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { RecoilRoot } from "recoil";
import RecoilContextProvider from "@/lib/recoilContextProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const metadata = {
  title: "Blog Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <RecoilContextProvider> {children}</RecoilContextProvider>
      </body>
    </html>
  );
}
